name = "mlda"
version = "0.1.0"
keywords = ["logic", "distributed systems"]
defaultTargets = ["mlda"]

[leanOptions]
pp.unicode.fun = true
pp.fieldNotation = false
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[lean_lib]]
name = "mlda"
